version: '3'

services:
   web:
      build: 
         context: './image_www'
         args:
            hard_mode: 0 # set to 0 or 1
      container_name: 'ctf_sql_web'
      tty: 'true'
      restart: 'on-failure'
      networks:
         net-10.9.0.0:
            ipv4_address: '10.9.0.2'
      ports:
         - '808:80/tcp'
         - '4434:443/tcp'
   mysql:
      build: './image_mysql'
      container_name: 'ctf_sql_mysql'
      tty: 'true'
      restart: 'on-failure'
      networks:
         net-10.9.0.0:
            ipv4_address: '10.9.0.3'

networks:
  net-10.9.0.0:
      name: 'net-10.9.0.0'
      ipam:
         config:
            - subnet: '10.9.0.0/24'
