version: "3"

services:
   server:
      build: 
         context: ./src/server
         args: 
            BUFFER_SIZE: 100
      container_name: hard_fmt_str_srv
      tty: true
      ports:
         - "8888:7777"
      restart: on-failure

