version: "3.8"

services:
   ubuntu:
      build: 
         context: ./image_ubuntu
         args: 
            SEED_USER_PASS: "dees"
      tty: true
      ports:
         - "49152-65535:22"
      deploy:
         mode: replicated
         replicas: 5
         restart_policy:
            condition: on-failure
            max_attempts: 10
