version: "3.8"

services:
   ubuntu:
      build: 
         context: ./image_ubuntu
         args: 
            VULN_PROG_BUF_SIZE: 100
            SEED_USER_PASS: "dees"
      #container_name: ctf_ret_libc_ubuntu
      #restart: unless-stopped
      tty: true
      ports:
         - "49152-65535:22"
      deploy:
         mode: replicated
         replicas: 5
         restart_policy:
            condition: on-failure
            max_attempts: 10
